#!/bin/bash
set -e
CACHE_DIR=/mnt/sdb/JHW/pip_cache
TMP_DIR=/mnt/sdb/JHW/tmp
BUILD_DIR=/mnt/sdb/JHW/build
PIP=/mnt/sdb/JHW/envs/work38_cu11/bin/pip

# 모든 임시 파일과 빌드 파일을 /mnt/sdb/JHW에 저장
mkdir -p "$CACHE_DIR" "$TMP_DIR" "$BUILD_DIR"

# 환경 변수 설정
export TMPDIR="$TMP_DIR"
export TMP="$TMP_DIR"
export TEMP="$TMP_DIR"
export PIP_CACHE_DIR="$CACHE_DIR"
export PIP_BUILD_DIR="$BUILD_DIR"

echo "Installing adabound~=0.0.5..."
$PIP install --cache-dir "$CACHE_DIR" "adabound~=0.0.5" || echo "Failed to install adabound~=0.0.5, continuing..."
echo ""
echo "Installing addict~=2.4.0..."
$PIP install --cache-dir "$CACHE_DIR" "addict~=2.4.0" || echo "Failed to install addict~=2.4.0, continuing..."
echo ""
echo "Installing alabaster~=0.7.12..."
$PIP install --cache-dir "$CACHE_DIR" "alabaster~=0.7.12" || echo "Failed to install alabaster~=0.7.12, continuing..."
echo ""
echo "Installing albumentations~=1.0.2..."
$PIP install --cache-dir "$CACHE_DIR" "albumentations~=1.0.2" || echo "Failed to install albumentations~=1.0.2, continuing..."
echo ""
echo "Installing babel~=2.8.0..."
$PIP install --cache-dir "$CACHE_DIR" "babel~=2.8.0" || echo "Failed to install babel~=2.8.0, continuing..."
echo ""
echo "Installing chumpy~=0.70..."
$PIP install --cache-dir "$CACHE_DIR" "chumpy~=0.70" || echo "Failed to install chumpy~=0.70, continuing..."
echo ""
echo "Installing compress-pickle~=1.2.0..."
$PIP install --cache-dir "$CACHE_DIR" "compress-pickle~=1.2.0" || echo "Failed to install compress-pickle~=1.2.0, continuing..."
echo ""
echo "Installing configparser~=5.0.1..."
$PIP install --cache-dir "$CACHE_DIR" "configparser~=5.0.1" || echo "Failed to install configparser~=5.0.1, continuing..."
echo ""
echo "Installing cython~=0.29..."
$PIP install --cache-dir "$CACHE_DIR" "cython~=0.29" || echo "Failed to install cython~=0.29, continuing..."
echo ""
echo "Installing deepspeech-gpu~=0.9.2..."
$PIP install --cache-dir "$CACHE_DIR" "deepspeech-gpu~=0.9.2" || echo "Failed to install deepspeech-gpu~=0.9.2, continuing..."
echo ""
echo "Installing docker-pycreds~=0.4.0..."
$PIP install --cache-dir "$CACHE_DIR" "docker-pycreds~=0.4.0" || echo "Failed to install docker-pycreds~=0.4.0, continuing..."
echo ""
echo "Installing docutils~=0.16..."
$PIP install --cache-dir "$CACHE_DIR" "docutils~=0.16" || echo "Failed to install docutils~=0.16, continuing..."
echo ""
echo "Installing dominate~=2.6.0..."
$PIP install --cache-dir "$CACHE_DIR" "dominate~=2.6.0" || echo "Failed to install dominate~=2.6.0, continuing..."
echo ""
echo "Installing easydict~=1.9..."
$PIP install --cache-dir "$CACHE_DIR" "easydict~=1.9" || echo "Failed to install easydict~=1.9, continuing..."
echo ""
echo "Installing face-alignment~=1.3.3..."
$PIP install --cache-dir "$CACHE_DIR" "face-alignment~=1.3.3" || echo "Failed to install face-alignment~=1.3.3, continuing..."
echo ""
echo "Installing facenet-pytorch~=2.5.1..."
$PIP install --cache-dir "$CACHE_DIR" "facenet-pytorch~=2.5.1" || echo "Failed to install facenet-pytorch~=2.5.1, continuing..."
echo ""
echo "Installing flatbuffers..."
$PIP install --cache-dir "$CACHE_DIR" "flatbuffers" || echo "Failed to install flatbuffers, continuing..."
echo ""
echo "Installing freetype-py~=2.2.0..."
$PIP install --cache-dir "$CACHE_DIR" "freetype-py~=2.2.0" || echo "Failed to install freetype-py~=2.2.0, continuing..."
echo ""
echo "Installing gdown~=3.12.2..."
$PIP install --cache-dir "$CACHE_DIR" "gdown~=3.12.2" || echo "Failed to install gdown~=3.12.2, continuing..."
echo ""
echo "Installing gitdb~=4.0.5..."
$PIP install --cache-dir "$CACHE_DIR" "gitdb~=4.0.5" || echo "Failed to install gitdb~=4.0.5, continuing..."
echo ""
echo "Installing gitpython~=3.1.11..."
$PIP install --cache-dir "$CACHE_DIR" "gitpython~=3.1.11" || echo "Failed to install gitpython~=3.1.11, continuing..."
echo ""
echo "Installing google-pasta~=0.2.0..."
$PIP install --cache-dir "$CACHE_DIR" "google-pasta~=0.2.0" || echo "Failed to install google-pasta~=0.2.0, continuing..."
echo ""
echo "Installing h5py==3.7.0..."
$PIP install --cache-dir "$CACHE_DIR" "h5py==3.7.0" || echo "Failed to install h5py==3.7.0, continuing..."
echo ""
echo "Installing hickle==5.0.2..."
$PIP install --cache-dir "$CACHE_DIR" "hickle==5.0.2" || echo "Failed to install hickle==5.0.2, continuing..."
echo ""
echo "Installing hydra-core~=1.0.5..."
$PIP install --cache-dir "$CACHE_DIR" "hydra-core~=1.0.5" || echo "Failed to install hydra-core~=1.0.5, continuing..."
echo ""
echo "Installing imagesize~=1.2.0..."
$PIP install --cache-dir "$CACHE_DIR" "imagesize~=1.2.0" || echo "Failed to install imagesize~=1.2.0, continuing..."
echo ""
echo "Installing imgaug~=0.4.0..."
$PIP install --cache-dir "$CACHE_DIR" "imgaug~=0.4.0" || echo "Failed to install imgaug~=0.4.0, continuing..."
echo ""
echo "Installing importlib-resources~=5.1.0..."
$PIP install --cache-dir "$CACHE_DIR" "importlib-resources~=5.1.0" || echo "Failed to install importlib-resources~=5.1.0, continuing..."
echo ""
echo "Installing insightface~=0.5..."
$PIP install --cache-dir "$CACHE_DIR" "insightface~=0.5" || echo "Failed to install insightface~=0.5, continuing..."
echo ""
echo "Installing kaggle~=1.5.12..."
$PIP install --cache-dir "$CACHE_DIR" "kaggle~=1.5.12" || echo "Failed to install kaggle~=1.5.12, continuing..."
echo ""
echo "Installing keras-preprocessing~=1.1.2..."
$PIP install --cache-dir "$CACHE_DIR" "keras-preprocessing~=1.1.2" || echo "Failed to install keras-preprocessing~=1.1.2, continuing..."
echo ""
echo "Installing librosa==0.9.2..."
$PIP install --cache-dir "$CACHE_DIR" "librosa==0.9.2" || echo "Failed to install librosa==0.9.2, continuing..."
echo ""
echo "Installing lightning-bolts~=0.4.0..."
$PIP install --cache-dir "$CACHE_DIR" "lightning-bolts~=0.4.0" || echo "Failed to install lightning-bolts~=0.4.0, continuing..."
echo ""
echo "Installing mediapipe>=0.8.10..."
$PIP install --cache-dir "$CACHE_DIR" "mediapipe>=0.8.10" || echo "Failed to install mediapipe>=0.8.10, continuing..."
echo ""
echo "Installing memory-profiler~=0.58.0..."
$PIP install --cache-dir "$CACHE_DIR" "memory-profiler~=0.58.0" || echo "Failed to install memory-profiler~=0.58.0, continuing..."
echo ""
echo "Installing mmcv-full~=1.5.0..."
$PIP install --cache-dir "$CACHE_DIR" "mmcv-full~=1.5.0" || echo "Failed to install mmcv-full~=1.5.0, continuing..."
echo ""
echo "Installing munch~=2.5.0..."
$PIP install --cache-dir "$CACHE_DIR" "munch~=2.5.0" || echo "Failed to install munch~=2.5.0, continuing..."
echo ""
echo "Installing numpy>=1.23.1..."
$PIP install --cache-dir "$CACHE_DIR" "numpy>=1.23.1" || echo "Failed to install numpy>=1.23.1, continuing..."
echo ""
echo "Installing omegaconf~=2.0.6..."
$PIP install --cache-dir "$CACHE_DIR" "omegaconf~=2.0.6" || echo "Failed to install omegaconf~=2.0.6, continuing..."
echo ""
echo "Installing onnx~=1.10.2..."
$PIP install --cache-dir "$CACHE_DIR" "onnx~=1.10.2" || echo "Failed to install onnx~=1.10.2, continuing..."
echo ""
echo "Installing onnxruntime-gpu>=1.9.0..."
$PIP install --cache-dir "$CACHE_DIR" "onnxruntime-gpu>=1.9.0" || echo "Failed to install onnxruntime-gpu>=1.9.0, continuing..."
echo ""
echo "Installing opencv-python~=4.5.5..."
$PIP install --cache-dir "$CACHE_DIR" "opencv-python~=4.5.5" || echo "Failed to install opencv-python~=4.5.5, continuing..."
echo ""
echo "Installing opencv-python-headless~=4.5.3.56..."
$PIP install --cache-dir "$CACHE_DIR" "opencv-python-headless~=4.5.3.56" || echo "Failed to install opencv-python-headless~=4.5.3.56, continuing..."
echo ""
echo "Installing opt-einsum~=3.3.0..."
$PIP install --cache-dir "$CACHE_DIR" "opt-einsum~=3.3.0" || echo "Failed to install opt-einsum~=3.3.0, continuing..."
echo ""
echo "Installing pathtools~=0.1.2..."
$PIP install --cache-dir "$CACHE_DIR" "pathtools~=0.1.2" || echo "Failed to install pathtools~=0.1.2, continuing..."
echo ""
echo "Installing pillow~=8.1.2..."
$PIP install --cache-dir "$CACHE_DIR" "pillow~=8.1.2" || echo "Failed to install pillow~=8.1.2, continuing..."
echo ""
echo "Installing plotly==5.8.0..."
$PIP install --cache-dir "$CACHE_DIR" "plotly==5.8.0" || echo "Failed to install plotly==5.8.0, continuing..."
echo ""
echo "Installing prettytable~=2.4.0..."
$PIP install --cache-dir "$CACHE_DIR" "prettytable~=2.4.0" || echo "Failed to install prettytable~=2.4.0, continuing..."
echo ""
echo "Installing protobuf~=3.14.0..."
$PIP install --cache-dir "$CACHE_DIR" "protobuf~=3.14.0" || echo "Failed to install protobuf~=3.14.0, continuing..."
echo ""
echo "Installing psutil~=5.7.3..."
$PIP install --cache-dir "$CACHE_DIR" "psutil~=5.7.3" || echo "Failed to install psutil~=5.7.3, continuing..."
echo ""
echo "Installing pyasn1-modules~=0.2.8..."
$PIP install --cache-dir "$CACHE_DIR" "pyasn1-modules~=0.2.8" || echo "Failed to install pyasn1-modules~=0.2.8, continuing..."
echo ""
echo "Installing python-speech-features~=0.6..."
$PIP install --cache-dir "$CACHE_DIR" "python-speech-features~=0.6" || echo "Failed to install python-speech-features~=0.6, continuing..."
echo ""
echo "Installing pytorch-lightning==1.4.9..."
$PIP install --cache-dir "$CACHE_DIR" "pytorch-lightning==1.4.9" || echo "Failed to install pytorch-lightning==1.4.9, continuing..."
echo ""
echo "Installing pyzmq~=22.0.3..."
$PIP install --cache-dir "$CACHE_DIR" "pyzmq~=22.0.3" || echo "Failed to install pyzmq~=22.0.3, continuing..."
echo ""
echo "Installing scikit-sound~=0.2.3..."
$PIP install --cache-dir "$CACHE_DIR" "scikit-sound~=0.2.3" || echo "Failed to install scikit-sound~=0.2.3, continuing..."
echo ""
echo "Installing scipy>=1.8.1..."
$PIP install --cache-dir "$CACHE_DIR" "scipy>=1.8.1" || echo "Failed to install scipy>=1.8.1, continuing..."
echo ""
echo "Installing sentry-sdk~=0.19.2..."
$PIP install --cache-dir "$CACHE_DIR" "sentry-sdk~=0.19.2" || echo "Failed to install sentry-sdk~=0.19.2, continuing..."
echo ""
echo "Installing setuptools~=54.2.0..."
$PIP install --cache-dir "$CACHE_DIR" "setuptools~=54.2.0" || echo "Failed to install setuptools~=54.2.0, continuing..."
echo ""
echo "Installing shapely~=1.7.1..."
$PIP install --cache-dir "$CACHE_DIR" "shapely~=1.7.1" || echo "Failed to install shapely~=1.7.1, continuing..."
echo ""
echo "Installing smmap~=3.0.4..."
$PIP install --cache-dir "$CACHE_DIR" "smmap~=3.0.4" || echo "Failed to install smmap~=3.0.4, continuing..."
echo ""
echo "Installing subprocess32~=3.5.4..."
$PIP install --cache-dir "$CACHE_DIR" "subprocess32~=3.5.4" || echo "Failed to install subprocess32~=3.5.4, continuing..."
echo ""
echo "Installing tb-nightly~=2.5.0a20201210..."
$PIP install --cache-dir "$CACHE_DIR" "tb-nightly~=2.5.0a20201210" || echo "Failed to install tb-nightly~=2.5.0a20201210, continuing..."
echo ""
echo "Installing tensorboard-data-server~=0.6.1..."
$PIP install --cache-dir "$CACHE_DIR" "tensorboard-data-server~=0.6.1" || echo "Failed to install tensorboard-data-server~=0.6.1, continuing..."
echo ""
echo "Installing timm~=0.4.9..."
$PIP install --cache-dir "$CACHE_DIR" "timm~=0.4.9" || echo "Failed to install timm~=0.4.9, continuing..."
echo ""
echo "Installing torchfile>=0.1.0..."
$PIP install --cache-dir "$CACHE_DIR" "torchfile>=0.1.0" || echo "Failed to install torchfile>=0.1.0, continuing..."
echo ""
echo "Installing torchgeometry>=0.1.2..."
$PIP install --cache-dir "$CACHE_DIR" "torchgeometry>=0.1.2" || echo "Failed to install torchgeometry>=0.1.2, continuing..."
echo ""
echo "Installing torchmetrics==0.6.2..."
$PIP install --cache-dir "$CACHE_DIR" "torchmetrics==0.6.2" || echo "Failed to install torchmetrics==0.6.2, continuing..."
echo ""
echo "Installing trimesh~=3.14.1..."
$PIP install --cache-dir "$CACHE_DIR" "trimesh~=3.14.1" || echo "Failed to install trimesh~=3.14.1, continuing..."
echo ""
echo "Installing wandb~=0.10.30..."
$PIP install --cache-dir "$CACHE_DIR" "wandb~=0.10.30" || echo "Failed to install wandb~=0.10.30, continuing..."
echo ""
echo "Installing watchdog~=0.10.3..."
$PIP install --cache-dir "$CACHE_DIR" "watchdog~=0.10.3" || echo "Failed to install watchdog~=0.10.3, continuing..."
echo ""
echo "Installing wrapt~=1.12.1..."
$PIP install --cache-dir "$CACHE_DIR" "wrapt~=1.12.1" || echo "Failed to install wrapt~=1.12.1, continuing..."
echo ""
echo "Installing youtube-dl~=2021.6.6..."
$PIP install --cache-dir "$CACHE_DIR" "youtube-dl~=2021.6.6" || echo "Failed to install youtube-dl~=2021.6.6, continuing..."
echo ""